### ISSUE TITLE
Mark Docs

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2289]
- [x] Break mark into multiple pages, one page per each mark type -- @sirahd 

- [x] Add missing mark types
   - List missing ones. For each, list idea about good examples to show

- [ ] Add more examples for existing types
  - [ ] Ranged Mark
     - [ ] timeline https://vega.github.io/vega/examples/timelines/

**Comment by kanitw** [comment]
- [ ] Update each mark's intro to be more descriptive.  (What are they good for etc.)  We can actually borrow a lot of text from [Vega docs](https://vega.github.io/vega/docs/marks/line/).

**Comment by kanitw** [comment]
Here is a sketch for a potential `type.yml`
```
TopLevelFacetedUnitSpec:
  padding:
    - Number
    - Object
  selection: Selection
  transform: "Transform[]"
  mark:
    - Mark
    - CompositeMark
  encoding: Encoding
```
