### ISSUE TITLE
Allow replacing type for properties in docs

### ISSUE THREAD

**Issue by YuhanLu** [vega/vega-lite#2299]
Now we have some type as `Mark`, `Interpolate`, etc in [docs](https://vega.github.io/vega-lite/docs/mark.html).
We should make them String so user can easily understand.

**Comment by kanitw** [comment]
I think it would be better to allow replacing certain types with a specific value?

**Comment by kanitw** [comment]
- spec.md
  - [ ] `Padding` => `Number | Object`

**Comment by kanitw** [comment]
Potential `type.yml`

```
TopLevelFacetedUnitSpec:
  padding:
    - Number
    - Object
  selection: Selection
  transform: "Transform[]"
  mark:
    - Mark
    - CompositeMark
  encoding: Encoding

DataFormat:
  type: String
```
